### ISSUE TITLE
[feature request] expose the base amount of each ore type in the config

### ISSUE THREAD

**Issue by Zygus42** [MightyPirates/BedrockOres#18]
Currently the config has this: veinYieldBaseScale, which affects the total amount of all ores, but there is an underlying assumption of how much iron ore is base amount as compared to say gold ore.  In my testing some of the amounts are ok for my new world (gold, lapis, diamonds), but others are way too much (iron), but if I adjust veinYieldBaseScale down to make iron work, then the others are too low to make them worth finding.

**Comment by fnuecke** [comment]
That's what the JSON configs are for :)

In your .minecraft/config/bedrockores directory you'll either find a `bedrock_veins.json` (older versions, feel free to delete this) or `_example.json` (newer version). This also documents the format of thos JSON files. To adjust the yields of iron patches, add an entry like this:
```
  {
    "state": {
      "name": "minecraft:iron_ore"
    },
    "yieldMin": 100,
    "yieldMax": 125
  }
```

Either add that to one of the existing JSON files, or create a new one (but in that case don't forget to throw a pair of `[` and `]` around that).

For the default settings, see [the config dir in the repo](https://github.com/MightyPirates/BedrockOres/tree/master-MC1.11/src/main/resources/assets/bedrockores/config).

Please leave this open as a reminder so I can add an explanation of this to the readme and on Curse.

**Comment by Zygus42** [comment]
Ah - didn't see that there was a separate folder in the configs dir as well as the .cfg - I must have 1000+ files and folders in my test config folder, so not always easy to see.  Unusual setup - most mods would have the .cfg inside the folder.  But all good now that I know it's there :)  Thank you.

**Comment by fnuecke** [comment]
Ah, yeah, the main .cfg is just directly in the config dir because I'm using the standard Forge config system for that, and that puts it there. I'll put a section on the configuration in the readme of the repo and probably in the Curse description, too!
