### ISSUE TITLE
1.12 Crashing with Hopper

### ISSUE THREAD

**Issue by Zygus42** [MightyPirates/BedrockOres#2]
Bedrock Ores-MC1.12-1.0.0.6

Attached Hopper to bottom of Bedrock Miner and crash:
[crash-2017-08-24_23.11.22-server.txt](https://github.com/MightyPirates/BedrockOres/files/1249357/crash-2017-08-24_23.11.22-server.txt)

**Comment by fnuecke** [comment]
Thanks for reporting! Had my hasCapability and getCapabilities inconsistent, oops.
