### ISSUE TITLE
CTD with MC1.12-1.1.0.23

### ISSUE THREAD

**Issue by Thiana** [MightyPirates/BedrockOres#24]
I'm getting a consistent CTD with 1.1.0.23. The log is here (https://paste.ee/p/Y9ydR), and to replicate it create a creative world then fly straight in a random direction. The crash can take a few minutes to happen but it always happens. The ore configuration is here (https://paste.ee/p/YPNSJ; Yes the numbers are insane atm, will balance later). 

Versions:
* MC 1.12.1
* Forge 2467
* BedrockOres MC1.12-1.1.0.23

**Comment by fnuecke** [comment]
Gneh, looks like Minecraft causes neighbors to get loaded when setting a block... fixed in 7df7963870965a57c60b99d468d7468ad7fc515a.
New version coming shortly.

**Comment by Thiana** [comment]
Thank you :)
