### ISSUE TITLE
Compatibility with Bedrock B Gone

### ISSUE THREAD

**Issue by ghost** [MightyPirates/BedrockOres#25]
[removed]

**Comment by fnuecke** [comment]
Why'd you close it? It's pretty easy to add compat for that. In fact, I just did >_>

**Comment by ghost** [comment]
Sorry for closing it, I reported it, but then saw on the configs that Bedrock B Gone's custom blocks were off and since my issue was about them, but they weren't on, I closed it. I should've changed the text to reflect the fact that not even with custom blocks it was working. Sorry!

And thanks for the compat :)

**Comment by fnuecke** [comment]
Ah, I see, allrighty then :)
