### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Sunconure11** [MightyPirates/BedrockOres#27]
https://pastebin.com/xB4D8RyJ

Trying to slowly build my 1.12.1 port of my own pack, ran into this error.

**Comment by fnuecke** [comment]
Please update, this has already been fixed in 1.1.1 :)

**Comment by Sunconure11** [comment]
Sorry, twitch is giving me some issues with telling me when a mod has been updated.

**Comment by Sunconure11** [comment]
While Twitch is indeed having issues, was this update marked as 1.12.1 compatible? I'm not receiving any indicators to update.

**Comment by fnuecke** [comment]
It was, 1.1.2 is the latest approved one and marked appropriately: https://minecraft.curseforge.com/projects/bedrockores/files
I'll push a minor update in a bit (for #28), maybe that'll fix it on their end.
