### ISSUE TITLE
RFTools Builder voids blocks

### ISSUE THREAD

**Issue by Thiana** [MightyPirates/BedrockOres#28]
Any ores within the harvest area of a clearing quarry builder are simply voided. This allows the player to open holes in the bedrock.

RFTools is using `if (!state.getBlock().canEntityDestroy(state, world, pos, entityPlayer))` (https://github.com/McJty/RFTools/blob/da92211d2220f80a76f224c159f2c5e62e6c6cd2/src/main/java/mcjty/rftools/blocks/builder/BuilderTileEntity.java#L1109) to detect invalid blocks.

**Comment by fnuecke** [comment]
Ah, interesting. Sure, I can override that.

(Side note: that method, `canEntityDestroy` that is, what an ugly, ugly method, Minecraft at its best :X)

**Comment by Thiana** [comment]
Thanks :)
