### ISSUE TITLE
Random crash preventing world loading afterwards

### ISSUE THREAD

**Issue by Keltas** [MightyPirates/BedrockOres#3]
This is a heavily modded instance so it may be hard to reproduce this crash. It happened while I was going down the ladder. I am attaching the crash reports for first crash and crash on loading world. I am also attaching the game log from the original crash. I am assuming it is this mod causing it, because it was added right before this session and is mentioned in crash report.
[crash-2017-08-24_16.05.18-client.txt](https://github.com/MightyPirates/BedrockOres/files/1249676/crash-2017-08-24_16.05.18-client.txt)
[crash-2017-08-24_19.59.31-client.txt](https://github.com/MightyPirates/BedrockOres/files/1249675/crash-2017-08-24_19.59.31-client.txt)
[2017-08-24-7.log.txt](https://github.com/MightyPirates/BedrockOres/files/1249683/2017-08-24-7.log.txt)

**Comment by fnuecke** [comment]
Thanks for reporting, I'm a little confused why this didn't happen for me (because it kinda should have). Will be fixed in the next build!
