### ISSUE TITLE
[enhancement] Allow extraction cost multiplier

### ISSUE THREAD

**Issue by Thiana** [MightyPirates/BedrockOres#30]
It would be nice if we could alter the extraction cost per ores. For example both diamond and gold cost ~800rf per block. If gold had a modifier of 0.75 the cost would become 600rf/block, and diamond a 3.0 modifier the cost would be 2400rf/block.

This would allow more realistic extraction costs plus allow gating really valuable blocks behind higher power generation. Thank you.

**Comment by fnuecke** [comment]
Hmm, sure I guess, will think on how to best implement this.

**Comment by fnuecke** [comment]
df8f162aa8e1cd777ee029dec99ce1dc0ed2bd5f

In the JSON you can now specify an `extractionCooldownScale`, which is a multiplier applied to the extraction cooldown from the regular config when extracting a particular ore (defaulting to 1).

E.g.:
```json
  {
    "state": { "name": "minecraft:diamond_ore" },
    "extractionCooldownScale": 4
  }
```
Will make diamond take 4 times as long, thus make it 4 times as expensive.

Will be in v1.2.0.

**Comment by Thiana** [comment]
Perfect :) Thanks.
