### ISSUE TITLE
Config/Feature: Abyssalcraft support

### ISSUE THREAD

**Issue by BBoldt** [MightyPirates/BedrockOres#32]
[Abyssalcraft](https://minecraft.curseforge.com/projects/abyssalcraft) adds quite a few ores, and while I could probably add most of them manually, it would be nice if they were supported automatically.

Some of the ores in this mod are in different dimensions, and some of them are limited to specific biomes.

**Comment by fnuecke** [comment]
99ed4ee00783fa496401e300bce51e2a033ca250

Was a bit tricky to pull out the defaults, but I *think* I got them mostly right... feel free to [check them here](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/config/abyssalcraft.json).

**Comment by BBoldt** [comment]
They look to be correct, will let you know if I run into any issues.

**Comment by BBoldt** [comment]
Sort of offtopic, but if I were to make a config for another mod, could I PR it?

**Comment by fnuecke** [comment]
Absolutely! Just put it in a JSON file with the modid of the mod and add the name to the [`_index.json` file](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/config/_index.json) (just like [the other built-in defaults](https://github.com/MightyPirates/BedrockOres/tree/master-MC1.11/src/main/resources/assets/bedrockores/config)). The yields in those files should (roughly) be the the number of that ore that spawn per chunk with regular world gen. For the max values just multiply that with 1.25.
