### ISSUE TITLE
Crash in Nether

### ISSUE THREAD

**Issue by whichonespink44** [MightyPirates/BedrockOres#38]
Got this crash report when exploring the Nether:
https://gist.github.com/whichonespink44/f1cb94ba93a84ee4fbe22a1d03f81c4e

Log file:
[fml-client-latest.zip](https://github.com/MightyPirates/BedrockOres/files/1290945/fml-client-latest.zip)

Fyi... I was able to log back into my world after the crash and haven't experienced it again.

**Comment by fnuecke** [comment]
This should have been fixed at the latest in 1.2.2, please update :)

As unlikely as I hope it to be, if it happens a again with that version, please reopen with new log, thanks!
