### ISSUE TITLE
[Suggestion] Add support for modded dimensions

### ISSUE THREAD

**Issue by Jomeaga** [MightyPirates/BedrockOres#39]
I usually find myself doing my mining in the mining dimension from Aroma1997's mod because I don't want to destroy my overworld. Unfortunately I found that the bedrocks ores don't spawn in that dimension.

**Comment by fnuecke** [comment]
f7eddd1d0c8ef47cfc3728dbb497df098f79f007

While one of the ideas behind this mod was to make mining dimensions less... necessary, I guess nothing speaks against supporting them when they're present :P Added a new config option that allows changing the default dimension types; previously just `overwrold`, now also contains `miningworld` (the type of the Aroma1997 mining dimension).
