### ISSUE TITLE
Bedrock Ores can't be harvested with normal pickaxe

### ISSUE THREAD

**Issue by BakermanLP** [MightyPirates/BedrockOres#46]
We are trying to harvest Bedrock Ores with a standard pickaxe. Expected yield is decreased by one, but no ore drops. 

Used mod versions are here: https://github.com/BakermanLP/ProjectRET-AoT/blob/1.11.2/VERSIONS.md

This seams to be only a multiplayer / server problem.

Michael (aka BakermanLP)

**Comment by fnuecke** [comment]
IIRC when we last tried to track this down, it turned out this didn't happen on a regular Forge server; do you have any more insights what Sponge (?) does differently that is breaking this?

**Comment by BakermanLP** [comment]
On the first try to excavate one bedrock ore, this is shown on the consol of the server:
```
[09:03:29] [Server thread/WARN] [Sponge]: No entity type is registered for class net.minecraftforge.common.util.FakePlayer
```
I can confirm, that this is only a problem with bedrockores + spongeforge. Without spongeforge this is working fine. 

I have opened a issue on spongeforge issue tracker:
https://github.com/SpongePowered/SpongeForge/issues/1825

Full server log:
http://paste.ubuntu.com/25850428/

**Comment by fnuecke** [comment]
Added a comment. As mentioned there, that warning doesn't appear in the linked log from what I can tell? Just making sure it's the one you wanted to link.

Let's see what they say, if it's something I have to/can fix, or if it's up to SpongeForge.

**Comment by fnuecke** [comment]
From what I understand it is acknowledged that this is a problem with SpongeForge, so it is now tracked via the linked issue. Closing this.
