### ISSUE TITLE
Better Config Explanation for Adding Modded Ores

### ISSUE THREAD

**Issue by Dragnier** [MightyPirates/BedrockOres#48]
I understand the modid:orename bit, but what does properties: { } need to contain? Can properties be empty? Where/how do I specify metadata or whatever to pick the correct ore? Everything I've tried has failed to spawn any of the ore I'm trying to add even with the weight turned up trying to force it to spawn.

**Comment by Dragnier** [comment]
Also, could you add a command to display in game what the percentage chance of an ore is to spawn? Perhaps add it to /bedrockores list so each one listed also shows that spawn chance?

**Comment by fnuecke** [comment]
Added some more info in 02ab14f82281c927b278d650dd3631186c54d92d and added the percentages in 991894d9d9e0e2c694727f2787ac0d4f3dd7d095.

To also have it here: properties are what you see in the brackets of some blocks in the debug view (F3) in the lower right. This is basically what metadata once was (and, for now, on the lowest still is). Basically if some blocks share one ID they are differentiated by the properties of the block state. Typically mod ores share one block id and just differ in the state. If in F3 you see `block_id[prop_name=prop_value]` then that translates to `{"name": "block_id", "properties": {"prop_name": "prop_value"}}`.
