### ISSUE TITLE
Can I repost the mod？

### ISSUE THREAD

**Issue by forestbat** [MightyPirates/BedrockOres#49]
I‘m a Chinese player and translator on [](http://www.mcbbs.net/portal.php)，like your bedrock ore very much，but we can't download it from curseforge easily because of GFW（Great Fire Wall），so I want to repost it on mcbbs——we'll claim the mod‘s author is you and recommend players to download on curse。

**Comment by fnuecke** [comment]
Well, in this case I suppose I have no reason to say no. So yeah, go ahead. Thanks for asking :)

(Not that I could actually forbid you from doing so, among other things due to the license the mod is under.)
