### ISSUE TITLE
breaks bedrockores on single hit

### ISSUE THREAD

**Issue by jiuribu** [MightyPirates/BedrockOres#50]
normal diamond pick axe , ti-con pix , even bedrock miner destroys literaly "core" with single hit

game does not crash , its only does render it in pink and , bedrock ores are destroyed instantly

no idea why but its annoying loosing over 3000 ores for no reason
![2017-12-17_23 35 02](https://user-images.githubusercontent.com/23649842/34084601-c67454f2-e383-11e7-9744-84f8f884c217.png)

**Comment by jiuribu** [comment]
good thing they still generate even with flatbedrock mod , no idea if thats the reason for this bug

**Comment by jiuribu** [comment]
found bedrock ore from IE , so its working , for now the only assumtion is that unloaded block is "harshen soul ore" which suppose to explode if u mine it,  not with special tool , also its only semi trasparent ore

"harshen castle mod"

**Comment by fnuecke** [comment]
You should be able to see what the ore is supposed to be in the debug view (F3).
Tho it'd have to manually added as a valid ore to even be put into a bedrock ore... either disable that, or you can blacklist it (rather, all ores from that mod) using the `oreModBlacklist` config option.
