### ISSUE TITLE
A method for prospecting

### ISSUE THREAD

**Issue by ghost** [MightyPirates/BedrockOres#51]
It would be useful to have some built in method for prospecting a chunk from the surface to see if it contained any bedrock ores, as finding them otherwise can be rather laborious. This would also be beneficial to a modpack that, for example, had bedrock ores as the only source of ore.

**Comment by fnuecke** [comment]
This is basically what [Scannable](https://github.com/MightyPirates/Scannable) is for; in fact, originally it would've almost been part of this mod, but then I decided to make it its own thing with a bunch more options :P
