### ISSUE TITLE
Tiered Bedrock Miner

### ISSUE THREAD

**Issue by ShaCraft** [MightyPirates/BedrockOres#53]
I am working on a pack that is using your mod here. Great mod btw, I love the concept. I have been looking for something like this for some time.  Is there any chance of adding NBT support?

On with the suggestions.

1. I was thinking of a tier system for the miner. have it limit what ore a t1-t4 could mine (for progressions).
Like a t1 could only mine iron and copper (modded would need a config matching the type). 

2. have options to give diamonds rather than the ore. (config option for what item to give other then the ore?)

3. have a setting that some ores will only spawn x distance from spawn. IE i'd like an option to have uranium only spawn after 2500 blocks. In my pack this is a very dangerous place to be.

there is more i just can't think of it off hand. i'll come back and add more as we progress on the pack. I think the above would add to the mod greatly in any pack. Thanks for all the work you have done! and thanks for considering my suggestions.

=S=
RG_Sha

**Comment by fnuecke** [comment]
1. Mm, not against it in principle. Just adds more complexity than I have to to work with at the time. Will leave this open as a reminder as I might come back to it somewhen.

2. I'd honestly rather not. For one, I like that this way you potentially need some more infrastructure to process the outputs, for two it's just so much simpler and more robust on the implementation side. Making the miner emulate block-breaking is beyond the scope I'd like the mod to be. Sorry.

3. Added a setting for this via 1bee5c8c05400f6c08c03e5e148dac98cfacc64e, `veinMinSpawnDistance`.

**Comment by micspam** [comment]
I know this is an equally large a request, but the addition of having "clones" of the miner that each read off a separate set of configs would be appreciated.

The ability to have, for example, a pack progression that goes from Slow Fuel->Fast Fuel->Ramping electricity would legitimately be gamechanging.
