### ISSUE TITLE
[1.11.2] Client Crash on generating new world

### ISSUE THREAD

**Issue by BakermanLP** [MightyPirates/BedrockOres#55]
Starting our modpack and generating a new world results in the following crash-report

http://paste.ubuntu.com/26436176/

Used Versions:
- Bedrock Ores-MC1.11.2-1.2.5.52.jar
- and many other mods

Michael

**Comment by fnuecke** [comment]
Hmm, interesting. This means there's some biome that doesn't have a registry name... wasn't aware that was possible. Adding a null check.

**Comment by BakermanLP** [comment]
Thanks

fnuecke <notifications@github.com> schrieb am Di., 30. Jan. 2018, 19:26:
