### ISSUE TITLE
Bug(?): Log throws error when using dimension IDs in custom .json

### ISSUE THREAD

**Issue by Ithronyar** [MightyPirates/BedrockOres#60]
The documentation says that there are two possible settings for the custom .json entry "dimensionSelector": "type" and "id". The problem is that using "id" (in, for example, a configuration for iron ore) produces an error message in the log saying:
`[main/ERROR] [bedrockores]: Dictionary type not supported for world selectors (used in config for 'minecraft:iron_ore').`

Using "type" produces no errors.

Even though "id" produces an error, it still loads and _seems_ to generate just fine when a numerical dimension ID is used, so it appears to just be a minor parsing bug. Or maybe I'm doing something wrong, I don't know.

Example .json to reproduce: https://pastebin.com/11kQ5dfM

**Comment by fnuecke** [comment]
Ah, yeah, there was a `break` missing there. Thanks, fixed!
