### ISSUE TITLE
Question: How do I specify meta data values in JSON files?

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MightyPirates/BedrockOres#63]
Specifically, I'd like to add `thermalfoundation:ore` with a meta data value of 3 to the config in order to disable lead. Is this possible?

**Comment by TheCowMonarch** [comment]
Perhaps [this](https://github.com/MightyPirates/BedrockOres/blob/master-MC1.11/src/main/resources/assets/bedrockores/config/thermalfoundation.json) will help?

**Comment by fnuecke** [comment]
As you probably could have guessed from the link above, you specify those by using their block state properties. To disable TF lead, create a custom ore config JSON with something like this in it, untested:
```json
{
  "state": {
    "name": "thermalfoundation:ore",
    "properties": {
      "type": "lead"
    }
  },
  "enabled": false
}
```
