### ISSUE TITLE
allowPlayerMining=false not working

### ISSUE THREAD

**Issue by SlyCedix** [MightyPirates/BedrockOres#66]
I have allowPlayerMining set to false in my config, but I can still mine bedrock ores: https://www.youtube.com/watch?v=T6aznWqiX8E (Don't mind the audio, was watching a podcast at the time)

**Comment by fnuecke** [comment]
Can't reproduce this, neither singleplayer nor multiplayer. Make sure you have this correctly on the server. If that's not it and it does not happen with Bedrock Ores on its own, try narrowing down which mod interaction might cause this, thanks.
