### ISSUE TITLE
[1.12.2] 1 Question/bug

### ISSUE THREAD

**Issue by TheSnowyChickens** [MightyPirates/BedrockOres#67]
1.12.2
Forge 2747
BRO: 1.2.6.41

Hello,
is your mod compatible with "JustEnoughDimensions" (JED)?
I created a JED "100" dimension and set the dimension to "100" in your config, but in the dimension 100 is nothing in the bedrock.

Edit: It only dont work with the main config dimension option.

Thx

**Comment by fnuecke** [comment]
Dunno, haven't used JED. You can check what dimension you're in using `/bedrockores info` and also get a list of what's valid to spawn in bedrock where you're at, hope that'll help.
