### ISSUE TITLE
Request: Compatibility with Hardcore Spelunking

### ISSUE THREAD

**Issue by Crowfooted** [MightyPirates/BedrockOres#68]
Spelunking adds bedrock in between natural cave systems to force players to navigate caves for mining instead of strip mining. Bedrock Ores does not generate any ores in the bedrock placed by Spelunking, even if the maximum generation height in BO config is set high, and the world generator weight/priority is set higher (later) than in Spelunking's config.

In conjunction with this, it would also be useful to be able to tell BO to generate more than one vein of bedrock ore per chunk.

**Comment by XvBUSHvX** [comment]
I'd like to second this request. I think it's a great idea.

**Comment by fnuecke** [comment]
Sorry, won't update for the older MC versions.  In the new one this is possible using MC's data driven world gen.
