### ISSUE TITLE
[Suggestion] Use block name instead of numerical ids in tileentity NBT

### ISSUE THREAD

**Issue by wormzjl** [MightyPirates/BedrockOres#69]
Hello. I would like to use some 3rd party tool to customize generation of bedrock ores. But the problem I have encountered is that bedrock ores currently use the numerical id instead of block name to store the ore information, which might not be consistent between saves.
So I would like to know if it's possible to allow the use of formats such as modid:blockname in TE info?

**Comment by fnuecke** [comment]
Sorry, won't update for the older MC versions.
