### ISSUE TITLE
[Question] Change Power Requirement for Miner

### ISSUE THREAD

**Issue by davqvist** [MightyPirates/BedrockOres#70]
Hi, love your mod. I want to use it in my modpack and wanted to change the power requirements of the Miners. I looked in the config and found minerEfficiency, minerEfficiencyExternalPower and minerEfficiencyInternalPower. But I am not sure if I understand the description of those values correctly. They all talk about the mining time, but I like to keep the mining time the same, just lower the power requirements. Can you help me what I need to change to achieve this?

**Comment by fnuecke** [comment]
Probably not of interest to you anymore (apologies), but for future reference: time in this context was meant as in "burn time", i.e. how long the miner can operate for. Extraction speed is unchanged.
