### ISSUE TITLE
infinite ore support

### ISSUE THREAD

**Issue by kit-sunei** [MightyPirates/BedrockOres#71]
while i love the concept of having less exploration to find ores, i like the idea of having One vein be the only vein i need even more

is it possible for there to be an "infinite ore" option, so that say, finding bedrock ores could be more rare, but when you do find them, they turn out to be infinite?

(i checked and did not find a relevant issue)

**Comment by ghost** [comment]
For some reason, I had it in my head that this was how the mod worked already. I hoped to use this to encourage the use of minecarts for mining.
I was thinking once the initial deposit runs out they can slowly regenerate. Maybe the miner could bring up mixed veins like IE including mining refuse (gravel, cobblestone, etc.).

**Comment by fnuecke** [comment]
Apologies for not replying back then, forgot to check on this repo for a long time.

For posterity: not planning on adding the extra logic for this, you can just crank up the yields to insane numbers where it's pretty much impossible to fully exhaust a bedrock ore.
