### ISSUE TITLE
How do I use the item name instead of the digital ID?

### ISSUE THREAD

**Issue by tangzixiang-hash** [MightyPirates/BedrockOres#77]
Hello, I encountered a problem when using this mod on MC version 1.12. When I tried to edit the existing bedrock ore through NBTedit, I found that I could n’t start. I could not use the digital ID displayed in JEI to enter other mods I am wondering if I can modify the type of bedrock ore by the name of the item, so I hope to get your help. Thank you

The above content is translated using Google Translate. If there are any errors, please forgive me.
![批注 2020-01-29 232939](https://user-images.githubusercontent.com/60438085/73370502-4a562d00-42ef-11ea-93f8-88ff961fa7b0.png)
![批注 2020-01-29 232906](https://user-images.githubusercontent.com/60438085/73370503-4a562d00-42ef-11ea-9724-9719f2f8d4e4.png)

**Comment by fnuecke** [comment]
Sorry, won't update for the older MC versions.  In the version for MC1.19.2+ it's just the block state name, since the substate hacks of the olden days are pretty much gone.
