### ISSUE TITLE
Min Y level to start generating config option [Enhancement]

### ISSUE THREAD

**Issue by Dr-Mic** [MightyPirates/BedrockOres#78]
Is it possible to add a min Y lvl config option to start generating the ores at? I thought it would be cool to have nodes of bedrock on the surface to set up mining at but I can't force the mod to generate them on the bedrock nodes, it just has to happen by chance. Unfortunately this is very infrequent because of the many more places it can spawn it at the bottom of the world.

**Comment by fnuecke** [comment]
Sorry, won't update for the older MC versions.  Can be configured using the new data driven worldgen in the versions for MC1.19.2+.
