### ISSUE TITLE
Weight config wont work

### ISSUE THREAD

**Issue by Krutoy242** [MightyPirates/BedrockOres#79]
Changing the `weight` in config `.json` file wont affect generation. 
Other options like "widthMin" works fine.

Config related to osmium:
```
{
    "state": {
      "name": "mekanism:oreblock",
      "properties": {
        "type": "osmium"
      }
    },
    "weight": 100,
    "widthMin": 5,
    "widthMax": 7,
    "countMin": 10,
    "countMax": 14,
    "yieldMin": 128,
    "yieldMax": 160,
    "group": "osmium",
    "groupOrder": "mekanism"
  },
```

Ingrame result: 
<img src="https://i.imgur.com/J3Q9gHv.png" width=300>

Visible rare distribution with Scannable scanner: https://i.imgur.com/DyLL22T.png

Expect that osmium would spawn 10 times often then other ore's.
Am i doing something wrong?

**Comment by fnuecke** [comment]
Sorry, won't update for the older MC versions.  World gen for new versions has been drastically simplified.
